services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/dotnotes/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: dotnotes_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  
  # nodeapi:
  #   container_name: apicontainer
  #   build: ./backend
  #   image: nodeapi:v1
  #   volumes:
  #     - $HOME/dotnotes/api:/code
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   environment:
  #     DB_HOST: mysqldb
  #     DB_PORT: 3306
  #     DB_USER: 'admin'
  #     DB_PASSWORD: 'letmein'
  #     DB_NAME: dotnotes_db
  #     DB_CONNECTION_LIMIT: 20
  #     SERVICE_TAGS: prod
  #     SERVICE_NAME: nodeapi
  #     SERVER_PORT: 3000
  #   depends_on:
  #     - mysqldb
  #   networks:
  #     - internalnet
  
  # viteapp:
  #   container_name: appcontainer
  #   build: ./frontend
  #   image: viteapp:v1
  #   volumes:
  #     - $HOME/dotnotes/app:/code
  #   ports:
  #     - 5173:5173
  #   expose:
  #     - 5173
  #   environment:
  #     SERVICE_TAGS: prod
  #     SERVICE_NAME: viteapp
  #     SERVICE_PORT: 5173
  #   depends_on:
  #     - nodeapi
  #   networks:
  #     - internalnet


networks:
  internalnet:
    driver: bridge
    